---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.5
    - 1.6
    - 1.7
  env:
    global:
      - GO15VENDOREXPERIMENT=1
  script:
    - go build github.com/Ch3ck/Go-Away/hello/numbers.go
